Create bank repository and current repository.
aleska351/CurrencyExchangeRate pull request #1
Opened 2020-12-02 00:38 UTC by aleska351

Added method retrieve, create and delete.

2020-12-06 10:51 UTC, Andriireva requested changes

2020-12-06 10:51 UTC, Andriireva commented on build.gradle
> +    //runtimeOnly 'org.postgresql:postgresql'
delete unused dependency

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/CurrencyexchangerateApplication.java
> +//        System.out.println(context.getBean("nameFromString"));
delete unused code

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/dao/BankRepository.java
> +    Optional<List<Bank>> retrieveAll();
Make it return LIst<Bank> without Optional

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/dao/CurrencyRepository.java
> +    Optional<List<Currency>> retrieveAllCurrenciesByBankId(Long bankId);
Make it return List<Currency> without Optional

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/dao/impl/BankRepositoryImpl.java
> +        LOGGER.info("================BankRepository constructor is called===========");
it is better to make it on debug level

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/dao/impl/BankRepositoryImpl.java
> +        LOGGER.info("retrieve bank with id {} ", id);
put it on debug level

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/dao/impl/BankRepositoryImpl.java
> +        currencyRepository.deleteAllByBankId(id);
It is not needed on Repository level

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/dao/impl/BankRepositoryImpl.java
> +    private final CurrencyRepository currencyRepository;
It is bad practice to use another repository in current repository. Repository is a simple and "dump" class that do a single action, it does not serve as a logic class

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/dao/impl/CurrencyRepositoryImpl.java
> +
remove empty rows

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/dao/impl/CurrencyRepositoryImpl.java
> +
remove 1 row

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/domain/Bank.java
> +    }
It is better to move it to a separate file

2020-12-06 10:51 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/mapper/CurrencyRowMapper.java
> +public class CurrencyRowMapper implements RowMapper<Currency> {
it is a good point that you made it as bean.

2020-12-06 12:00 UTC, aleska351 reviewed
Review code on your recommendation

2020-12-10 07:32 UTC, Andriireva commented on src/main/java/com/goncharenko/currencyexchangerate/dto/CurrencyDTO.java
> +@Component
Зачем нужен компонент? Вроде как инжекта нигде нет на этот класс.

2021-05-11 20:59 UTC, closed without merging